module.exports = {
	ra: {
		action: {
			export: 'Eksportuoti',
			add_filter: 'Pridėti filtrą',
			add: 'Pridėti',
			back: 'Atgal',
			bulk_actions: '1 pasirinktas |||| %{smart_count} pasirinktas',
			cancel: 'Atšaukti',
			clear_input_value: 'Aišku',
			clone: 'Dublikatas',
			confirm: 'Patvirtinkite',
			create: 'Sukurti',
			delete: 'Ištrinti',
			edit: 'Redaguoti',
			list: 'Sąrašas',
			refresh: 'Atnaujinkite',
			remove_filter: 'Nuimkite filtrą',
			remove: 'Ištrinti',
			save: 'Išsaugoti',
			search: 'Paieška',
			show: 'Vaizdas',
			sort: 'Rūšiavimas',
			undo: 'Atšaukti',
			expand: 'Atskleisti',
			close: 'Uždaryti',
		},
		boolean: {
			true: 'Taip',
			false: 'Ne',
			null: '',
		},
		page: {
			create: 'Sukurti %{name}',
			dashboard: 'Namai',
			edit: '%{name} #%{id}',
			error: 'Kažkas negerai',
			list: '%{name}',
			loading: 'Pakrovimas',
			not_found: 'Nerastas',
			show: '%{name} #%{id}',
			empty: 'Nėra %{name}.',
			invite: 'Ar norite pridėti dar vieną?',
		},
		input: {
			file: {
				upload_several:
					'Vilkite failus čia arba spustelėkite, kad pasirinktumėte.',
				upload_single: 'Vilkite failą čia arba spustelėkite norėdami pasirinkti.',
			},
			image: {
				upload_several:
					'Vilkite vaizdą čia arba spustelėkite, kad pasirinktumėte.',
				upload_single:
					'Vilkite vaizdus čia arba spustelėkite, jei norite pasirinkti.',
			},
			references: {
				all_missing: 'Nerasta jokių susijusių duomenų',
				many_missing: 'Kai kurių susijusių duomenų nėra.',
				single_missing: 'Susietas objektas negalimas',
			},
			password: {
				toggle_visible: 'Slėpti slaptažodį',
				toggle_hidden: 'Rodyti slaptažodį',
			},
		},
		message: {
			about: 'Pagalba',
			are_you_sure: 'Ar tu tikras?',
			bulk_delete_content:
				'Ar tikrai norite ištrinti %{name}? |||| Ar tikrai norite ištrinti objektus naudodami %{smart_count}?',
			bulk_delete_title:
				'Ištrinti %{name} |||| Ištrinti %{smart_count} %{name}',
			delete_content: 'Ar tikrai norite ištrinti šį elementą?',
			delete_title: 'Ištrinti %{name} #%{id}',
			details: 'Aprašymas',
			error: "Užklausos proceso metu įvyko klaida ir jos negalima užpildyti.",
			invalid_form: 'Forma nėra tinkamai užpildyta, patikrinkite, ar nėra klaidų',
			loading: 'Atsisiunčiama, palaukite ...',
			no: 'Ne',
			not_found:
				'URL klaida arba naudojate neteisingą nuorodą',
			yes: 'Taip',
		},
		navigation: {
			no_results: 'Rezultatų nerasta',
			no_more_results: '%{page} puslapis iš numeracijos, pabandykite ankstesnį',
			page_out_of_boundaries: '%{page} puslapis iš ribų',
			page_out_from_end: 'Neįmanoma perkelti paskutinio puslapio',
			page_out_from_begin: 'Puslapio numeris negali būti mažesnis nei 1',
			page_range_info: '%{offsetBegin}-%{offsetEnd} iš %{total}',
			page_rows_per_page: 'Eilučių puslapyje:',
			next: 'Kitas',
			prev: 'Ankstesnis',
		},
		auth: {
			auth_check_error: 'Jei norite tęsti, prisijunkite',
			user_menu: 'Profilis',
			username: 'Vartotojo vardas',
			password: 'Slaptažodis',
			sign_in: 'Prisijunkite',
			sign_in_error: 'Autentifikuoti nepavyko, bandykite dar kartą',
			logout: 'Išeik',
		},
		notification: {
			updated: 'Prekė atnaujinta |||| %{smart_count} atnaujinta',
			created: 'Prekė sukurta',
			deleted: 'Punktas išbrauktas |||| %{smart_count} ištrinta',
			bad_item: 'Prekė negalioja',
			item_doesnt_exist: 'Prekės nėra',
			http_error: 'Serverio klaida',
			data_provider_error:
				'Klaida dataProvider, patikrinkite pultą',
			i18n_error:
				'Nepavyko įkelti nurodytos kalbos vertimo',
			canceled: 'Operacija atšaukta',
			logged_out: 'Jūsų sesija baigta, pabandykite vėl prisijungti/vėl prisijungti',
		},
		validation: {
			required: 'Privaloma',
			minLength: 'Mažiausias simbolių skaičius %{min}',
			maxLength: 'Didžiausias ženklų skaičius %{max}',
			minValue: 'Mažiausia vertė yra %{min}',
			maxValue: 'Vertė gali būti %{max} arba mažesnė',
			number: 'Turi būti skaičius',
			email: 'Netinkamas el. Pašto adresas',
			oneOf: 'Turi būti vienas iš: %{options}',
			regex: 'uri būti tokio formato (regexp): %{pattern}',
		},
	},
};
