module.exports = {
	ra: {
		action: {
			export: 'Eksportuoti',
			add_filter: 'Pridėti filtrą',
			add: 'Pridėti',
			back: 'Atgal',
			bulk_actions: '1 pasirinktas |||| %{smart_count} pasirinkti',
			cancel: 'Atšaukti',
			clear_input_value: 'Ištrinti lauko reikšmę',
			clone: 'Klonuoti',
			confirm: 'Patvirtinti',
			create: 'Sukurti',
			delete: 'Ištrinti',
			edit: 'Redaguoti',
			list: 'Sąrašas',
			refresh: 'Atnaujinti',
			remove_filter: 'Nuimti filtrą',
			remove: 'Ištrinti',
			save: 'Išsaugoti',
			search: 'Paieška',
			show: 'Peržiūrėti',
			sort: 'Rikiuoti',
			undo: 'Panaikinti',
			expand: 'Išskleisti',
			close: 'Uždaryti',
		},
		boolean: {
			true: 'Taip',
			false: 'Ne',
			null: '',
		},
		page: {
			create: 'Sukurti %{name}',
			dashboard: 'Namai',
			edit: '%{name} #%{id}',
			error: 'Klaida',
			list: '%{name}',
			loading: 'Įkeliami duomenys',
			not_found: 'Nerasta',
			show: '%{name} #%{id}',
			empty: 'Nėra %{name}.',
			invite: 'Pakviesti',
		},
		input: {
			file: {
				upload_several:
					'Vilkite failus čia arba spustelėkite, kad įkelti kelis.',
				upload_single: 'Vilkite failą čia arba spustelėkite norėdami įkelti.',
			},
			image: {
				upload_several:
					'Vilkite nuotraukas čia arba spustelėkite, kad įkeltumėte kelias.',
				upload_single:
					'Vilkite nuotrauką čia arba spustelėkite, jei norite įkelti.',
			},
			references: {
				all_missing: 'Nerasta jokių susijusių duomenų',
				many_missing: 'Kai kurių susijusių duomenų nėra.',
				single_missing: 'Susietas objektas nerastas',
			},
			password: {
				toggle_visible: 'Slėpti slaptažodį',
				toggle_hidden: 'Rodyti slaptažodį',
			},
		},
		message: {
			about: 'Apie',
			are_you_sure: 'Ar esate tikras?',
			bulk_delete_content:
				'Ar tikrai norite ištrinti %{name}? |||| Ar tikrai norite ištrinti objektus naudodami %{smart_count}?',
			bulk_delete_title:
				'Ištrinti %{name} |||| Ištrinti %{smart_count} %{name}',
			delete_content: 'Ar tikrai norite ištrinti šį elementą?',
			delete_title: 'Ištrinti %{name} #%{id}',
			details: 'Aprašymas',
			error: "Užklausos proceso metu įvyko klaida ir jos negalima užpildyti.",
			invalid_form: 'Forma nėra tinkamai užpildyta, patikrinkite, ar nėra klaidų',
			loading: 'Įkeliama, palaukite ...',
			no: 'Ne',
			not_found: 'URL klaida arba naudojate neteisingą nuorodą',
			yes: 'Taip',
		},
		navigation: {
			no_results: 'Rezultatų nerasta',
			no_more_results: 'Daugiau rezultatų nėra',
			page_out_of_boundaries: '%{page} puslapis už ribų',
			page_out_from_end: 'Neįmanoma perkelti paskutinio puslapio',
			page_out_from_begin: 'Puslapio numeris negali būti mažesnis nei 1',
			page_range_info: '%{offsetBegin}-%{offsetEnd} iš %{total}',
			page_rows_per_page: 'Eilučių puslapyje:',
			next: 'Kitas',
			prev: 'Ankstesnis',
		},
		auth: {
			auth_check_error: 'Jei norite tęsti, prisijunkite',
			user_menu: 'Profilis',
			username: 'Vartotojo vardas',
			password: 'Slaptažodis',
			sign_in: 'Prisijunkite',
			sign_in_error: 'Prisijungti nepavyko, bandykite dar kartą',
			logout: 'Atsijungti',
		},
		notification: {
			updated: 'Prekė atnaujinta |||| %{smart_count} atnaujintos',
			created: 'Prekė sukurta |||| %{smart_count} sukurtos',
			deleted: 'Punktas išbrauktas |||| %{smart_count} ištrinti',
			bad_item: 'Prekė negalioja',
			item_doesnt_exist: 'Prekės nėra',
			http_error: 'Serverio klaida',
			data_provider_error:
				'Klaida dataProvider, patikrinkite pultą',
			i18n_error:
				'Nepavyko įkelti nurodytos kalbos vertimo',
			canceled: 'Operacija atšaukta',
			logged_out: 'Jūsų sesija baigėsi, prisijunkite iš naujo',
		},
		validation: {
			required: 'Privaloma užpildyti',
			minLength: 'Mažiausias simbolių skaičius %{min}',
			maxLength: 'Didžiausias ženklų skaičius %{max}',
			minValue: 'Mažiausia vertė yra %{min}',
			maxValue: 'Vertė gali būti %{max} arba mažesnė',
			number: 'Turi būti skaičius',
			email: 'Netinkamas el. pašto adresas',
			oneOf: 'Turi būti vienas iš: %{options}',
			regex: 'Turi būti tokio formato (regexp): %{pattern}',
		},
	},
};
